<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: xnguyenh
 * Date: Tue, 09 Dec 2025 08:38:36 +0000
 */

$conf['title'] = 'Thesis';
$conf['template'] = 'reskin';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['numatomo']['server'] = 'https://localhost:8080/';
$conf['plugin']['numatomo']['feature-flags'] = 'enableLinkTracking,requireConsent,requireCookieConsent';
