# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 13 Oct 2025 18:47:05 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

xnguyenh:$2y$10$zei5PohaNf69yF1Yt2ajsuUGhHVWkfcH7XvLal5TLmeZAPl2o9H7a:Duong Nguyen Hoang:550550@mail.muni.cz:admin,user
